name: go

on: ["push", "pull_request"]

jobs:
  ci  :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
     # - name: Run build
     #   run: go build .
      - name: Run linters
        run: |
          go vet ./...
          golint ./...
          test -z $(gofmt -d ./...)
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
      - name: Run testing
        run: go test -v ./...