name: test

on: [ "push", "pull_request" ]

jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -v -covermode=atomic -coverprofile="coverage.txt" ./...
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v2
        with:
         fail_ci_if_error: true
         file: ./coverage.txt